import "react-router";

declare module "react-router" {
  interface RouterContextProvider {
    cloudflare: {
      env: Env;
      ctx: ExecutionContext;
    };
  }
}

// `Route.LoaderArgs` / `Route.ActionArgs` (generated by `react-router typegen`)
// resolve `RouterContextProvider` through the `react-router/internal` types
// tree (`dist/development/lib/...`), which is a distinct type-declaration
// tree from the one the `react-router` package specifier resolves to
// (`dist/production/index.d.ts`, per its `exports` map). Both must be
// augmented for `context.cloudflare` to type-check everywhere.
declare module "../node_modules/react-router/dist/development/lib/router/utils.js" {
  interface RouterContextProvider {
    cloudflare: {
      env: Env;
      ctx: ExecutionContext;
    };
  }
}
